/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.shotgunkeys.app;

public final class R {
    public static final class attr {
    }
    public static final class color {
        /**  Tactical Accents 
         */
        public static final int accent_amber=0x7f070004;
        public static final int accent_amber_glow=0x7f070005;
        public static final int accent_cyan=0x7f07000a;
        public static final int accent_green=0x7f070008;
        public static final int accent_green_glow=0x7f070009;
        public static final int accent_red=0x7f070006;
        public static final int accent_red_glow=0x7f070007;
        public static final int bg_card=0x7f070002;
        public static final int bg_card_selected=0x7f070003;
        /**  Tactical Dark Palette 
         */
        public static final int bg_dark=0x7f070000;
        public static final int bg_surface=0x7f070001;
        public static final int border_active=0x7f07000f;
        /**  Borders and Dividers 
         */
        public static final int border_color=0x7f07000e;
        public static final int btn_action_bg=0x7f070014;
        /**  Button Backgrounds 
         */
        public static final int btn_blast_bg=0x7f070010;
        public static final int btn_blast_ripple=0x7f070011;
        public static final int btn_reload_bg=0x7f070012;
        public static final int btn_reload_ripple=0x7f070013;
        public static final int text_muted=0x7f07000d;
        /**  Typography Colors 
         */
        public static final int text_primary=0x7f07000b;
        public static final int text_secondary=0x7f07000c;
    }
    public static final class drawable {
        public static final int btn_action_green=0x7f020000;
        public static final int btn_secondary=0x7f020001;
        public static final int btn_tactical_blast=0x7f020002;
        public static final int btn_tactical_reload=0x7f020003;
        public static final int card_tactical_active_bg=0x7f020004;
        public static final int card_tactical_bg=0x7f020005;
        public static final int floating_widget_bg=0x7f020006;
    }
    public static final class id {
        public static final int btn_fire_blast=0x7f0a0006;
        public static final int btn_preset_test=0x7f0a0019;
        public static final int btn_pump_reload=0x7f0a0007;
        public static final int btn_toggle_accessibility=0x7f0a0005;
        public static final int card_preset_root=0x7f0a0014;
        public static final int card_service_status=0x7f0a0001;
        public static final int floating_root=0x7f0a0012;
        public static final int layout_presets_container=0x7f0a000b;
        public static final int seekbar_volume=0x7f0a000d;
        public static final int switch_floating_widget=0x7f0a0011;
        public static final int switch_haptics=0x7f0a0010;
        public static final int switch_micro_dynamics=0x7f0a000e;
        public static final int switch_space_reload=0x7f0a000f;
        public static final int tv_btn_reset_stats=0x7f0a0008;
        public static final int tv_floating_icon=0x7f0a0013;
        public static final int tv_header_status_badge=0x7f0a0000;
        public static final int tv_preset_desc=0x7f0a0018;
        public static final int tv_preset_icon=0x7f0a0015;
        public static final int tv_preset_name=0x7f0a0016;
        public static final int tv_preset_selected_badge=0x7f0a0017;
        public static final int tv_service_indicator=0x7f0a0002;
        public static final int tv_service_status_text=0x7f0a0004;
        public static final int tv_service_title=0x7f0a0003;
        public static final int tv_stat_reloads=0x7f0a000a;
        public static final int tv_stat_shots_fired=0x7f0a0009;
        public static final int tv_volume_value=0x7f0a000c;
    }
    public static final class layout {
        public static final int activity_main=0x7f040000;
        public static final int floating_widget=0x7f040001;
        public static final int item_preset=0x7f040002;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f030000;
        public static final int ic_launcher_round=0x7f030001;
    }
    public static final class raw {
        public static final int arcade_blast=0x7f060000;
        public static final int arcade_reload=0x7f060001;
        public static final int cyber_blast_1=0x7f060002;
        public static final int cyber_blast_2=0x7f060003;
        public static final int cyber_reload_1=0x7f060004;
        public static final int cyber_reload_2=0x7f060005;
        public static final int doom_blast_1=0x7f060006;
        public static final int doom_blast_2=0x7f060007;
        public static final int doom_reload_1=0x7f060008;
        public static final int doom_reload_2=0x7f060009;
        public static final int real_shotgun_reload=0x7f06000a;
        public static final int shotgun_blast_1=0x7f06000b;
        public static final int shotgun_blast_2=0x7f06000c;
        public static final int shotgun_blast_3=0x7f06000d;
        public static final int shotgun_blast_4=0x7f06000e;
        public static final int shotgun_reload_1=0x7f06000f;
        public static final int shotgun_reload_2=0x7f060010;
        public static final int silenced_blast_1=0x7f060011;
        public static final int silenced_blast_2=0x7f060012;
        public static final int silenced_reload_1=0x7f060013;
        public static final int silenced_reload_2=0x7f060014;
        public static final int tactical_blast_1=0x7f060015;
        public static final int tactical_blast_2=0x7f060016;
        public static final int tactical_blast_3=0x7f060017;
        public static final int tactical_reload_1=0x7f060018;
        public static final int tactical_reload_2=0x7f060019;
    }
    public static final class string {
        public static final int accessibility_enable_prompt=0x7f080005;
        public static final int accessibility_service_desc=0x7f080002;
        public static final int app_name=0x7f080000;
        public static final int app_tagline=0x7f080001;
        public static final int btn_enable_service=0x7f080006;
        public static final int btn_fire_blast=0x7f080009;
        public static final int btn_pump_reload=0x7f08000a;
        public static final int btn_service_active=0x7f080007;
        public static final int preset_arcade=0x7f08001a;
        public static final int preset_arcade_desc=0x7f08001b;
        public static final int preset_cyberpunk=0x7f080018;
        public static final int preset_cyberpunk_desc=0x7f080019;
        public static final int preset_doom=0x7f080014;
        public static final int preset_doom_desc=0x7f080015;
        public static final int preset_realistic=0x7f080010;
        public static final int preset_realistic_desc=0x7f080011;
        public static final int preset_silenced=0x7f080016;
        public static final int preset_silenced_desc=0x7f080017;
        public static final int preset_tactical=0x7f080012;
        public static final int preset_tactical_desc=0x7f080013;
        /**  Presets 
         */
        public static final int presets_title=0x7f08000f;
        public static final int setting_floating_widget=0x7f080024;
        public static final int setting_floating_widget_sub=0x7f080025;
        public static final int setting_haptics=0x7f080022;
        public static final int setting_haptics_sub=0x7f080023;
        public static final int setting_micro_dynamics=0x7f08001e;
        public static final int setting_micro_dynamics_sub=0x7f08001f;
        public static final int setting_space_reload=0x7f080020;
        public static final int setting_space_reload_sub=0x7f080021;
        public static final int setting_volume=0x7f08001d;
        /**  Audio & Dynamics Settings 
         */
        public static final int settings_title=0x7f08001c;
        /**  Soundboard 
         */
        public static final int soundboard_title=0x7f080008;
        public static final int stat_reloads=0x7f08000d;
        public static final int stat_reset=0x7f08000e;
        public static final int stat_shots_fired=0x7f08000c;
        /**  Statistics 
         */
        public static final int stats_title=0x7f08000b;
        /**  Status & Alerts 
         */
        public static final int status_active=0x7f080003;
        public static final int status_inactive=0x7f080004;
        /**  Footer 
         */
        public static final int version_info=0x7f080026;
    }
    public static final class style {
        public static final int Theme_ShotgunKeys=0x7f090000;
    }
    public static final class xml {
        public static final int accessibility_service_config=0x7f050000;
    }
}
